### ISSUE TITLE
Homework + Extra Point

### ISSUE THREAD

**Issue by GeorgeAlexRob** [rstropek-teaching/turmrechnen-quiz-4bhif-AlexGeorgeRob#1]
Hello,

so I did the homework in [StackBlitz](https://stackblitz.com/) as requested for the Bonus Point.
Hope I did it right, sadly I was absent the last two units when you started Angular.

Greetings,
Alex Rob

**Homework Links:**
[Editor URL](https://stackblitz.com/edit/angular-7vrqts)
[App URL](https://angular-7vrqts.stackblitz.io)

**Comment by rstropek** [comment]
Hi @AlexGeorgeRob 

Well done, your extra point is secured.

Greetings,
Rainer Stropek.
